version: '3'

services:
  database:
    image: library/postgres:11-alpine
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRES_DB: main
    ports: [5432]

  redis:
    image: library/redis:5-alpine
    ports: [6379]
